# Generated by Django 3.0.2 on 2020-01-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_number',
            field=models.IntegerField(),
        ),
    ]
