# Generated by Django 3.0.2 on 2020-01-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20200115_0403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='pokedex_number',
        ),
    ]
