# Generated by Django 3.0.2 on 2020-01-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20200115_0440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemon',
            new_name='Trainer',
        ),
    ]
