# Generated by Django 3.0.2 on 2020-01-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_auto_20200115_0455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
